[pytest]
python_paths = backend/
DJANGO_SETTINGS_MODULE = zavarka39_shop.settings
norecursedirs = env/*
addopts = -vv -p no:cacheprovider --disable-warnings
testpaths = tests/
python_files = test_*.py